package com.samplecompany.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*Represents entity class for computer entity which includes  information about computer details like MAC address,IP address
* ,computer name, description also employee details to whom the computer can be assigned*/

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Computer {

    //unique identifier to the computer
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long computerId;

   //holds MAC address of the computer and it is the required field
    @Column(nullable = false)
    private String macAddress;

    //holds computer name of the computer and it is the required field.
    @Column(nullable = false)
    private String computerName;

    //holds the IP address of the computer and it is the required field.
    @Column(nullable = false)
    private String ipAddress;

    //Holds the Employee Abbreviation(Employee Name in 3 letters)  and limit of this 3 characters
    @Column(length = 3)
    private String employeeAlias;

    //Holds the description about the Computer
    @Column
    private String description;

    //Getters and Setters are generated by Lombok
}
